const EARLY_LEVELS = [
  {
    id: 1,
    handCount: 3,
    revealSeconds: 3,
    preShuffleDelayMs: 480,
    shuffleDurationMs: 720,
    pauseBetweenRoundsMs: 280,
    showTutorialArrow: true,
    guessTimeLimit: 9,
    shuffleCount: 2,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 2,
    handCount: 4,
    revealSeconds: 3,
    preShuffleDelayMs: 430,
    shuffleDurationMs: 650,
    pauseBetweenRoundsMs: 240,
    showTutorialArrow: true,
    guessTimeLimit: 8,
    shuffleCount: 3,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 3,
    handCount: 5,
    revealSeconds: 3,
    preShuffleDelayMs: 380,
    shuffleDurationMs: 560,
    pauseBetweenRoundsMs: 190,
    showTutorialArrow: false,
    guessTimeLimit: 7,
    shuffleCount: 5,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 4,
    handCount: 6,
    revealSeconds: 3,
    preShuffleDelayMs: 360,
    shuffleDurationMs: 540,
    pauseBetweenRoundsMs: 180,
    showTutorialArrow: false,
    guessTimeLimit: 7,
    shuffleCount: 5,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 5,
    handCount: 6,
    revealSeconds: 3,
    preShuffleDelayMs: 350,
    shuffleDurationMs: 520,
    pauseBetweenRoundsMs: 170,
    showTutorialArrow: false,
    guessTimeLimit: 7,
    shuffleCount: 6,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 6,
    handCount: 6,
    revealSeconds: 3,
    preShuffleDelayMs: 340,
    shuffleDurationMs: 500,
    pauseBetweenRoundsMs: 160,
    showTutorialArrow: false,
    guessTimeLimit: 6,
    shuffleCount: 6,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 7,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 330,
    shuffleDurationMs: 490,
    pauseBetweenRoundsMs: 150,
    showTutorialArrow: false,
    guessTimeLimit: 6,
    shuffleCount: 7,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 8,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 320,
    shuffleDurationMs: 475,
    pauseBetweenRoundsMs: 145,
    showTutorialArrow: false,
    guessTimeLimit: 6,
    shuffleCount: 8,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 9,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 310,
    shuffleDurationMs: 465,
    pauseBetweenRoundsMs: 140,
    showTutorialArrow: false,
    guessTimeLimit: 6,
    shuffleCount: 8,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 10,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 300,
    shuffleDurationMs: 455,
    pauseBetweenRoundsMs: 135,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 9,
    minTreatMoves: 2,
    enableFinalRotate: false,
    finalRotateChoices: []
  },
  {
    id: 11,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 290,
    shuffleDurationMs: 445,
    pauseBetweenRoundsMs: 130,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 9,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-2, 2]
  },
  {
    id: 12,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 285,
    shuffleDurationMs: 440,
    pauseBetweenRoundsMs: 125,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 9,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-3, 3]
  },
  {
    id: 13,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 280,
    shuffleDurationMs: 435,
    pauseBetweenRoundsMs: 120,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 9,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-3, 3]
  },
  {
    id: 14,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 275,
    shuffleDurationMs: 430,
    pauseBetweenRoundsMs: 118,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 9,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-4, 4]
  },
  {
    id: 15,
    handCount: 7,
    revealSeconds: 3,
    preShuffleDelayMs: 270,
    shuffleDurationMs: 425,
    pauseBetweenRoundsMs: 115,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-4, 4]
  },
  {
    id: 16,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 265,
    shuffleDurationMs: 420,
    pauseBetweenRoundsMs: 110,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5]
  },
  {
    id: 17,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 260,
    shuffleDurationMs: 415,
    pauseBetweenRoundsMs: 108,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5]
  },
  {
    id: 18,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 255,
    shuffleDurationMs: 410,
    pauseBetweenRoundsMs: 105,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 19,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 250,
    shuffleDurationMs: 405,
    pauseBetweenRoundsMs: 100,
    showTutorialArrow: false,
    guessTimeLimit: 5,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 20,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 245,
    shuffleDurationMs: 400,
    pauseBetweenRoundsMs: 98,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5, -6, 6]
  },
  {
    id: 21,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 240,
    shuffleDurationMs: 395,
    pauseBetweenRoundsMs: 95,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5, -6, 6]
  },
  {
    id: 22,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 235,
    shuffleDurationMs: 390,
    pauseBetweenRoundsMs: 92,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 23,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 230,
    shuffleDurationMs: 385,
    pauseBetweenRoundsMs: 90,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 24,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 225,
    shuffleDurationMs: 380,
    pauseBetweenRoundsMs: 88,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5, -6, 6]
  },
  {
    id: 25,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 220,
    shuffleDurationMs: 375,
    pauseBetweenRoundsMs: 86,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 10,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 26,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 215,
    shuffleDurationMs: 370,
    pauseBetweenRoundsMs: 84,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 27,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 210,
    shuffleDurationMs: 365,
    pauseBetweenRoundsMs: 82,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5, -6, 6]
  },
  {
    id: 28,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 205,
    shuffleDurationMs: 360,
    pauseBetweenRoundsMs: 80,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 29,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 200,
    shuffleDurationMs: 355,
    pauseBetweenRoundsMs: 78,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, 6]
  },
  {
    id: 30,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: 195,
    shuffleDurationMs: 350,
    pauseBetweenRoundsMs: 76,
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11,
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-5, 5, -6, 6]
  }
];

const MID_LEVELS = Array.from({ length: 20 }, (_, i) => {
  const id = i + 31;
  return {
    id,
    handCount: 8,
    revealSeconds: 3,
    preShuffleDelayMs: Math.max(150, 190 - i * 2),
    shuffleDurationMs: Math.max(270, 345 - i * 3),
    pauseBetweenRoundsMs: Math.max(50, 74 - i),
    showTutorialArrow: false,
    guessTimeLimit: 4,
    shuffleCount: 11 + Math.floor(i / 3),
    minTreatMoves: 2,
    enableFinalRotate: true,
    finalRotateChoices: [-6, -5, 5, 6]
  };
});

const LATE_LEVELS = Array.from({ length: 30 }, (_, i) => {
  const id = i + 51;
  const useEightHands = i >= 10;
  return {
    id,
    handCount: useEightHands ? 8 : 8,
    revealSeconds: 3,
    preShuffleDelayMs: Math.max(110, 150 - i),
    shuffleDurationMs: Math.max(210, 285 - i * 2),
    pauseBetweenRoundsMs: Math.max(35, 54 - Math.floor(i * 0.7)),
    showTutorialArrow: false,
    guessTimeLimit: useEightHands ? 3 : 4,
    shuffleCount: useEightHands ? 14 + Math.floor(i / 4) : 13 + Math.floor(i / 5),
    minTreatMoves: 3,
    enableFinalRotate: true,
    finalRotateChoices: useEightHands
      ? [-7, -6, -5, 5, 6, 7]
      : [-6, -5, 5, 6]
  };
});

export const LEVELS = [
  ...EARLY_LEVELS,
  ...MID_LEVELS,
  ...LATE_LEVELS
];